import { useState } from "react";
import { View, Text, ScrollView, StyleSheet, Platform, Pressable, Linking } from "react-native";
import { router } from "expo-router";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Ionicons } from "@expo/vector-icons";
import Colors from "@/constants/colors";

const faqs = [
  {
    question: "How do I perform a cash withdrawal using AEPS?",
    answer:
      "Go to the Home tab and tap 'Cash Withdrawal'. Enter the customer's Aadhaar number, bank, and amount. The customer authenticates with their biometric fingerprint to complete the transaction.",
  },
  {
    question: "What is a UTR number?",
    answer:
      "UTR (Unique Transaction Reference) is a 12-22 digit reference number generated by your bank after a successful UPI payment. You can find it in your UPI app's transaction history.",
  },
  {
    question: "My AEPS transaction failed but was deducted",
    answer:
      "If an AEPS transaction failed but the amount was deducted, it will be automatically refunded within 3-5 business days. Contact support if the refund is not received.",
  },
  {
    question: "How do I complete my KYC?",
    answer:
      "Go to the KYC tab and tap 'Start KYC Verification'. You will be guided through the PaySprint KYC process. Once approved, your AEPS services will be fully activated.",
  },
  {
    question: "I'm not receiving the OTP",
    answer:
      "Make sure your phone number is correct and has active network. Wait 30 seconds and try 'Resend OTP'. If the issue persists, check if SMS from ESTORE sender is blocked.",
  },
  {
    question: "Which banks are supported for AEPS?",
    answer:
      "RupyaSetu supports all major banks linked with Aadhaar including SBI, PNB, Bank of Baroda, Union Bank, Canara Bank, HDFC, ICICI, Axis Bank, and most regional rural and cooperative banks.",
  },
];

export default function HelpScreen() {
  const insets = useSafeAreaInsets();
  const topPadding = Platform.OS === "web" ? 67 : insets.top;
  const [expandedIndex, setExpandedIndex] = useState<number | null>(null);

  function toggleFaq(index: number) {
    setExpandedIndex(expandedIndex === index ? null : index);
  }

  return (
    <View style={[styles.container, { paddingTop: topPadding }]}>
      <View style={styles.header}>
        <Pressable onPress={() => router.back()} style={styles.backButton}>
          <Ionicons name="arrow-back" size={24} color={Colors.text} />
        </Pressable>
        <Text style={styles.headerTitle}>Help & Support</Text>
      </View>

      <ScrollView
        style={styles.scrollView}
        contentContainerStyle={{ paddingBottom: Platform.OS === "web" ? 34 : 40 }}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.contactCard}>
          <Text style={styles.contactTitle}>Need help?</Text>
          <Text style={styles.contactSub}>Reach out to us anytime</Text>
          <Pressable
            style={styles.contactBtn}
            onPress={() => Linking.openURL("mailto:support@rupyasetu.com")}
          >
            <Ionicons name="mail-outline" size={20} color="#fff" />
            <Text style={styles.contactBtnText}>Email Us</Text>
          </Pressable>
        </View>

        <Text style={styles.sectionTitle}>Frequently Asked Questions</Text>

        {faqs.map((faq, index) => (
          <Pressable key={index} style={styles.faqCard} onPress={() => toggleFaq(index)}>
            <View style={styles.faqHeader}>
              <Text style={styles.faqQuestion}>{faq.question}</Text>
              <Ionicons
                name={expandedIndex === index ? "chevron-up" : "chevron-down"}
                size={18}
                color={Colors.textTertiary}
              />
            </View>
            {expandedIndex === index && (
              <Text style={styles.faqAnswer}>{faq.answer}</Text>
            )}
          </Pressable>
        ))}
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 12,
    gap: 12,
  },
  backButton: {
    width: 44,
    height: 44,
    justifyContent: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
  },
  scrollView: {
    flex: 1,
    paddingHorizontal: 20,
  },
  contactCard: {
    backgroundColor: Colors.primary,
    borderRadius: 16,
    padding: 24,
    marginBottom: 24,
    alignItems: "center",
    gap: 6,
  },
  contactTitle: {
    fontSize: 20,
    fontFamily: "Inter_700Bold",
    color: "#fff",
  },
  contactSub: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: "rgba(255,255,255,0.8)",
    marginBottom: 12,
  },
  contactBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    marginTop: 6,
  },
  contactBtnText: {
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: "#fff",
  },
  sectionTitle: {
    fontSize: 16,
    fontFamily: "Inter_700Bold",
    color: Colors.text,
    marginBottom: 14,
  },
  faqCard: {
    backgroundColor: Colors.surface,
    borderRadius: 14,
    padding: 16,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  faqHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  faqQuestion: {
    flex: 1,
    fontSize: 14,
    fontFamily: "Inter_600SemiBold",
    color: Colors.text,
  },
  faqAnswer: {
    fontSize: 13,
    fontFamily: "Inter_400Regular",
    color: Colors.textSecondary,
    lineHeight: 20,
    marginTop: 12,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: Colors.borderLight,
  },
});
